workflows:
  android-workflow:
    name: Build APK
    environment:
      flutter: 3.29.2
      java: 17
    scripts:
      - name: Recreate Android project files
        script: | 
          flutter create --platforms=android .
      - name: Force Java 17
        script: |
          echo "android {
            compileOptions {
              sourceCompatibility JavaVersion.VERSION_17
              targetCompatibility JavaVersion.VERSION_17
            }
            kotlinOptions {
              jvmTarget = '17'
            }
          }" >> android/app/build.gradle
      - name: Get dependencies
        script: | 
          flutter pub get
      - name: Build APK
        script: | 
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
